# Generated by Django 5.2 on 2025-04-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='subject',
            new_name='class_room',
        ),
    ]
